query BlogCategory($id: Int) {
  blogCategories(where: {id: $id}) {
    id
    title
    order
    color
    articles {
      id
      uuid
      title
      content
      content_plain_text
      view_count
      order
      youtube_url
    }
  }
}
