query Products {
  products {
    id
    title
    price
    description
    order
    shop_url
    images {
      url
      alternativeText
    }
    features {
      title
      icon {
        url
        alternativeText
      }
    }
  }
}
