query Manuals {
  manuals {
    id
    slug
    title
    hidden
    product_image {
      url
      alternativeText
    }
    app {
      icon {
        url
        alternativeText
      }
    }
  }
}
