query Manuals($slug: String!) {
  manuals(where: {slug: $slug}) {
    id
    slug
    title
    hidden
    tag
    chapters {
      id
      title
      articles {
        id
        uuid
        title
        content
        published_at
      }
    }
    product_image {
      url
    }
    product_with_title_image {
      url
    }
    app {
      icon {
        url
      }
      download
      compatibility
    }
  }
}
