query Manuals($locale: String) {
  manuals(locale: $locale) {
    id
    slug
    title
    hidden
    tag
    product_image {
      url
      alternativeText
    }
    product_with_title_image {
      url
    }
    app {
      icon {
        url
        alternativeText
      }
    }
    locale
  }
}
