query Manuals($slug: String!, $locale: String) {
  manuals(where: {slug: $slug}, locale: $locale) {
    id
    slug
    title
    hidden
    tag
    chapters {
      id
      title
      order
      articles {
        id
        uuid
        title
        content
        order
      }
    }
    product_image {
      url
    }
    product_with_title_image {
      url
    }
    app {
      icon {
        url
      }
      download
      compatibility
      disclaimer
      android_store_url
      apple_store_url
    }
    products {
      id
      slug
      title
      pdf {
        id
        url
      }
    }
  }
}
