query Articles($uuid: String!, $locale: String) {
  articles(where: {uuid: $uuid}, locale: $locale) {
    id
    uuid
    slug
    title
    content
    chapter {
      id
      uuid
      slug
      title
      manual {
        id
        slug
        title
      }
    }
    locale
  }
}
