query popularArticles($sort: String, $limit: Int, $where: JSON) {
  articles(sort: $sort, limit: $limit, where: $where) {
    id
    uuid
    slug
    title
    content
    content_plain_text
    chapter {
      id
      slug
      title
      manual {
        id
        slug
        title
        tag
      }
    }
    type
    view_count
  }
}

