query Chapter($uuid: String!, $locale: String) {
  chapters(where: {uuid: $uuid}, locale: $locale) {
    id
    uuid
    manual {
      id
      slug
      title
    }
    title
    slug
    articles {
      id
      title
      slug
      uuid
    }
  }
}
